import fs from "node:fs";
import path from "node:path";
import { mergePackageJson, appendEnvExample, mergeWranglerConfig } from "./merge.js";

/** Dirs that belong inside src/ when create-next-app scaffolded with one.
 *  "content" rides along with lib so `lib/content.ts` can import
 *  `../content/content.json` under either layout. */
const SRC_SCOPED = new Set(["app", "lib", "components", "content"]);

function usesSrcDir(projectDir) {
  return fs.existsSync(path.join(projectDir, "src", "app"));
}

/** Map an overlay-relative path onto the project, respecting src/ layout. */
export function projectPath(projectDir, relPath) {
  const [head] = relPath.split(path.sep);
  if (usesSrcDir(projectDir) && SRC_SCOPED.has(head)) {
    return path.join(projectDir, "src", relPath);
  }
  return path.join(projectDir, relPath);
}

function copyDir(srcDir, projectDir, rel = "") {
  for (const entry of fs.readdirSync(path.join(srcDir, rel), { withFileTypes: true })) {
    const relPath = path.join(rel, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcDir, projectDir, relPath);
    } else {
      const dest = projectPath(projectDir, relPath);
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      // Overlays may intentionally overwrite (e.g. base and products both own
      // app/page.tsx). Apply order — base, then features, then product — means
      // "last writer wins" is the desired behavior.
      fs.copyFileSync(path.join(srcDir, relPath), dest);
    }
  }
}

/**
 * Apply one overlay (base/, features/<id>/, or products/<id>/) to a project:
 * copy files/, then merge its manifest. Returns post-install notes to show
 * the dev at the end.
 */
export function applyOverlay(projectDir, overlayDir) {
  const filesDir = path.join(overlayDir, "files");
  if (fs.existsSync(filesDir)) copyDir(filesDir, projectDir);

  const manifestPath = ["feature.json", "product.json", "overlay.json"]
    .map((f) => path.join(overlayDir, f))
    .find((p) => fs.existsSync(p));
  if (!manifestPath) return [];

  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  mergePackageJson(projectDir, manifest);
  appendEnvExample(projectDir, manifest.env);
  mergeWranglerConfig(projectDir, manifest);
  return manifest.postInstallNotes ?? [];
}

/** Write the generated config module the home page reads to render feature cards. */
export function writeTemplateConfig(projectDir, { product, features, version }) {
  const dest = projectPath(projectDir, path.join("lib", "template-config.ts"));
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const config = {
    product: product === "none" ? null : product,
    features,
    createdWith: `smm-create-app@${version}`,
    createdAt: new Date().toISOString(),
  };
  fs.writeFileSync(
    dest,
    "// Generated by smm-create-app — safe to edit if you add features later.\n" +
      `export const templateConfig = ${JSON.stringify(config, null, 2)} as const;\n`
  );
}
